---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /opt/couchdb

wp_dir: wordpress

python_pip_packages:
  - python-pip

python_sni_support_packages:
  - python-dev
  - libssl-dev
  - libffi-dev

default_docker_dependencies: []

# Repository to be used for the installation of the packages
docker_repo: "{{ docker_repo_ce_stable }}"

##
# Docker
##

# Name of the package providing Docker
docker_package_name: "docker-ce"

# Version of the Docker package to be installed.
# By default, the latest available version will be installed.
docker_package_version: ""

# Installation state of the Docker package.
# Set it to 'latest' to upgrade Docker to the latest version.
docker_package_state: present

# Extra packages that have to be installed together with Docker
# e.g. linux-image-extra-virtual on some Debian systems
docker_dependencies: "{{ default_docker_dependencies }}"

# Add the Unimelb proxy to the docker service to ensure
# imaged can be pulled from the Internet
docker_proxy: |
  [Service]
  Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/" "NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"


# State of the Docker deamon service
docker_service_state: "started"

# Whether the Docker service should start on boot
docker_service_enabled: "yes"

# Docker Deamon configuration
docker_daemon_config: {}

##
# Docker CLI
##

# Name of the package providing the Docker CLI
docker_cli_package_name: "docker-ce-cli"

# Version of the Docker CLI package to be installed.
docker_cli_package_version: ""

# Installation state of the Docker CLI package.
# Set it to 'latest' to upgrade the Docker CLI to the latest version.
docker_cli_package_state: present

##
# Docker Compose
##

# Version of the docker-compose package to be installed.
# By default, the latest available version will be installed.
docker_compose_version: ""

##
# Docker-py
##

# Name of the python-pip package providing docker-py
docker_py_package_name: "docker"

# Version of the docker-py package to be installed.
docker_py_package_version: ""

# Installation state of the docker-py package.
# Set it to 'latest' to upgrade the Docker CLI to the latest version.
docker_py_package_state: present

##
# Docker Users
##

# Name of the Docker group
docker_group_name: "docker"

# List of the users in the Docker group
docker_group_users:
  - "{{ ansible_user | default(ansible_user_id) }}"  # if ansible_user is not defined, we default to the ansible ansible_user_id fact

##
# Docker Swarm
##

# Docker swarm network can be define in order to be sure that
# swarm cluster doesn't overlap with you infrastructure
# docker_swarm_network: 10.10.8.0/24

# You can set any interface, that is listened by docker engine.
# e.g. docker_swarm_interface: "eth1"
docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377

##
# Role Switches
##

# Switches disabling the docker-engine, docker group and swarm-mode setup.
skip_repo: false        # if true, skips the setup of the docker repository
skip_containerd: false  # if true, skips the setup of containerd
skip_engine: false      # if true, skips the docker engine installation
skip_cli: false         # if true, skips the docker cli installation
skip_swarm: false       # if true, skips the swarm setup
skip_group: false       # if true, does not add the docker_admin_users to the docker_group_name
skip_docker_py: false   # if true, skips the installation of docker-py
skip_docker_compose: false  # if true, skips the installation of docker-compose