##
# Common
#

service_env_vars: "--env https_proxy=${https_proxy} --env http_proxy=${http_proxy} --env no_proxy=${no_proxy}"

##
# HA-Proxy
##

ha_proxy_port_couchdb: 8080
haproxy_path: "/opt/haproxy"
couchdb_port: 5984

##
# Harvester
##

harvester_path: "/opt/harvester"
swarm_manager_ip: "{{ groups['docker_swarm_manager'][0] }}"
harvester_sa_username: "harvester"
harvester_sa_password: "secret"
harvester_build_proxy: "http://wwwproxy.unimelb.edu.au:8000/"


harvester_historic_tweepy_auth: [
    ["X7zGj3Ow4bPu05Em8WGGsko3G", "VkYgRxRkid5Ru4cpU7QineZIK2icnpRIHpZpVGaH8RlSYCJIQG"],
    ["PmRzO6aE5UCwbU9e9hUWS0PKv","uV88V1zKlqyEIayVfWnLfCXyTKJngT2u6RUaGO4SpIEfeM4QLm"]
]

harvester_keywords: [
    "airbnb", "stayz", "zomato", "deliveroo", "hungrypanda",
    "lyft", "olacab", "#grab", "grabcar", "didirider", "menulog",
    "doordash", "etsy", "gumtree", "fiverr", "cookitoo", "uber",
    "taxify", "airtasker", "#freelancer", "parkhound", "campspace",
    "upwork", "designcrowd", "ratesetter", "urbansitter", "airly",
    "gocatch", "shebah", "bellhops", "channel40", "freightmatch",
    "wrappli", "zoom2u", "carnextdoor", "camplify", "kindershare",
    "quipmo", "thevolte", "bettercaring", "#blys", "classbento",
    "helpling"
]

harvester_regions: [
    "Melbourne", "Sydney", "Queensland", "Perth", "New South Wales", "Brisbane", "Tasmania",
    "Canberra", "Darwin", "Adelaide", "Hobart", "Western Australia", "South Australia", "Victoria"
]
harvester_historic_services: 2
harvester_live_services: 1

harvester_live_tweepy_auth: [
    ["7K0xu6SgVlnA7nJwNVVPZHgSD", "MHIEp3ibXDKkVSilriKdRFFduvJn55ow6zsYdcU710wyui1Nil"]
]
harvester_live_access_token: [
    ["7K0xu6SgVlnA7nJwNVVPZHgSD", "MHIEp3ibXDKkVSilriKdRFFduvJn55ow6zsYdcU710wyui1Nil"]
]

##
# CouchDB
##

couchdb_path: "/opt/couchdb/data"
cluster_size: 3
user: admin
pass: admin
version: "3.0.0"
cookie: "grp_33"
uuid: "a192aeb9904e6590849337933b001159"
couch_db_twitter_database_name: twitter
couch_service_account_uid: "1040"
couch_service_account_group: admin
