##
# HA-Proxy
##

ha_proxy_port_couchdb: 8080
haproxy_path: "/opt/haproxy"
couchdb_port: 5984

##
# CouchDB
##

couchdb_path: "/opt/couchdb/data"
cluster_size: 3
user: admin
pass: admin
version: '3.0.0'
cookie: 'grp_33'
uuid: 'a192aeb9904e6590849337933b001159'