---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /opt

python_pip_packages:
  - python-pip

python_sni_support_packages:
  - python-dev
  - libssl-dev
  - libffi-dev

##
# Docker
##

# Add the Unimelb proxy to the docker service to ensure
# imaged can be pulled from the Internet
docker_proxy: |
  [Service]
  Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/" "NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"


# State of the Docker deamon service
docker_service_state: "started"

# Whether the Docker service should start on boot
docker_service_enabled: "yes"

# Docker Deamon configuration
docker_daemon_config: {}

##
# Docker CLI
##

# Name of the package providing the Docker CLI
docker_cli_package_name: "docker-ce-cli"

# Version of the Docker CLI package to be installed.
docker_cli_package_version: ""

# Installation state of the Docker CLI package.
# Set it to 'latest' to upgrade the Docker CLI to the latest version.
docker_cli_package_state: present

##
# Docker Compose
##

# Version of the docker-compose package to be installed.
# By default, the latest available version will be installed.
docker_compose_version: ""

##
# Docker-py
##

# Name of the python-pip package providing docker-py
docker_py_package_name: "docker"

# Version of the docker-py package to be installed.
docker_py_package_version: ""

# Installation state of the docker-py package.
# Set it to 'latest' to upgrade the Docker CLI to the latest version.
docker_py_package_state: present

##
# Docker Users
##

# Name of the Docker group
docker_group_name: "docker"

# List of the users in the Docker group
docker_group_users:
  - "{{ ansible_user | default(ansible_user_id) }}"  # if ansible_user is not defined, we default to the ansible ansible_user_id fact

##
# Docker Swarm
##

# You can set any interface, that is listened by docker engine.
# e.g. docker_swarm_interface: "eth1"
docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377