# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: assignment2-vol-1
    vol_size: 10
  - vol_name: assignment2-vol-2
    vol_size: 10
  - vol_name: assignment2-vol-3
    vol_size: 10
  - vol_name: assignment2-vol-4
    vol_size: 10

# Security group
security_groups:
  - name: assignment2_ssh
    description: "Security group for SSH access"
    sg_rules:
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
  - name: nginx_test
    description: "Security group for SSH access"
    sg_rules:
      - protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0
  - name: docker_swarm
    description: "Security group for Docker Swarm"
    sg_rules:
      - protocol: tcp
        port_range_min: 2376
        port_range_max: 2377
        remote_group: docker_swarm
      - protocol: tcp
        port_range_min: 7946
        port_range_max: 7946
        remote_group: docker_swarm
      - protocol: udp
        port_range_min: 7946
        port_range_max: 7946
        remote_group: docker_swarm
      - protocol: udp
        port_range_min: 4789
        port_range_max: 4789
        remote_group: docker_swarm

# Instance
instances:
  - name: swarm-01
    volumes: ['assignment2-vol-1']
  - name: swarm-02
    volumes: ['assignment2-vol-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: assignment_2
instance_flavor: uom.mse.1c4g
instance_network: qh2-uom-internal

docker_swarm_managers: 2