# Project           : Gig Economy and its impact in Australia
# Team              : Group 33
# City              : Melbourne, Australia
# Authors           : Qing Feng Chye 770376, Sii Kim Lau 890511, Rohan Jahagirdar 835450
#                     Yun Liu 1046589, Shorye Chopra 689913
# Purpose           : Format external volumes, install XFS filesystem and mount on instance 
---
- name: Install dependencies
  tags: 'volumes'
  become: yes
  apt:
    name: ['xfsprogs']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Make file system
  tags: 'volumes'
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  with_items:
    - "{{ volumes }}"
  ignore_errors: yes

- name: Checking folders
  tags: 'volumes'
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  with_items:
    - "{{ volumes }}"
  ignore_errors: yes

- name: Create directory
  tags: 'volumes'
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"
  ignore_errors: yes

- name: Mount device
  tags: 'volumes'
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"
  ignore_errors: yes