---
- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: Add proxy in /etc/environment 
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au

- name: Reboot Machine
  reboot:
    reboot_timeout: 1800

- name: Install dependencies
  tags: always
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  tags: always
  pip:
    name: ['pip']
    state: latest

- name: Install python-pip.
  package:
    name: "{{ python_pip_packages }}"
    state: present
