# Project           : Gig Economy and its impact in Australia
# Team              : Group 33
# City              : Melbourne, Australia
# Authors           : Qing Feng Chye 770376, Sii Kim Lau 890511, Rohan Jahagirdar 835450
#                     Yun Liu 1046589, Shorye Chopra 689913
# Purpose           : Helper Tasks for populating Ansible in-memory inventory file
---
- name: Get Instance Information from Openstack Cloud
  os_server_info:
    server: '{{ item.name }}'
  loop: '{{ instances }}'
  register: os_instance_inventory

- name: Manager Node List    
  set_fact:
    manager_nodes: "{{ manager_nodes + [ os_instance_inventory.results[item|int] ] }}"
  with_sequence: start=0 end={{ swarm_managers_count - 1 }}

- name: Worker Node List    
  set_fact:
    worker_nodes: "{{ worker_nodes + [ os_instance_inventory.results[item|int] ] }}"
  with_sequence: start={{ swarm_managers_count }} end={{ os_instance_inventory.results|length - 1 }}

- name: Backend Node List
  set_fact:
    backend_nodes: "{{ backend_nodes + [ os_instance_inventory.results[item|int] ] }}"
  with_sequence: start=0 end={{ backend_nodes_count - 1 }}

- name: Frontend Node List    
  set_fact:
    frontend_nodes: "{{ frontend_nodes + [ os_instance_inventory.results[item|int] ] }}"
  with_sequence: start={{ backend_nodes_count }} end={{ os_instance_inventory.results|length - 1 }}

# Add hosts to Ansible in-memory inventory
- name: Add host SWARM Manager
  add_host:
    name: '{{ item.openstack_servers.0.public_v4 }}'
    groups: 
      - SWARM
      - docker_engine
      - docker_swarm_manager
  loop: '{{ manager_nodes }}'
  when: "(groups['docker_swarm_manager']|length < swarm_managers_count)"

- name: Add host SWARM Worker
  add_host:
    name: '{{ item.openstack_servers.0.public_v4 }}'
    groups: 
      - SWARM
      - docker_engine
      - docker_swarm_worker
  loop: '{{ worker_nodes }}'

- name: Add host Backend
  add_host:
    name: '{{ item.openstack_servers.0.public_v4 }}'
    groups: 
      - backend_nodes
  loop: '{{ backend_nodes }}'

- name: Add host Frontend
  add_host:
    name: '{{ item.openstack_servers.0.public_v4 }}'
    groups: 
      - frontend_nodes
  loop: '{{ frontend_nodes }}'

- name: inventory file
  debug:
    msg: Group Master {{ groups['docker_swarm_manager'] }} \n Group Worker {{ groups['docker_swarm_worker'] }} \n Group Backend {{ groups['backend_nodes'] }} \n Group Frontend {{ groups['frontend_nodes'] }}