- name: Create directory
  become: yes
  file:
    path: "{{ harvester_path }}"
    recurse: yes
    state: directory

- name: Copy files needed to build docker image on all backend nodes
  copy:
    src: "{{ item }}"
    dest: "{{ harvester_path }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - couchdb_requests.py
    - TwitterHarvester.py
    - requirements.txt
    - Dockerfile
  when: " 'backend_nodes' in group_names"

- name: Copy variables file
  template:
    src: "variables.json.j2"
    dest: "{{ harvester_path }}/variables.json"
    mode: '0755'
  when: " 'backend_nodes' in group_names"

- name: Build image and with build args
  docker_image:
    name: harvester:latest
    build:
      path: "{{ harvester_path }}"
      pull: yes
      use_config_proxy: yes
    source: build
  when: " 'backend_nodes' in group_names"

- name: Create Docker services for Harvester
  become: yes
  command: "docker service create 
    --mode replicated 
    --replicas 3 
    --name harvester-service  
    --constraint node.labels.type==backend
    {{ service_env_vars }}
    harvester:latest"
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"