
- name: Create Historic Harvesters
  include_tasks: harvester_historic.yaml
  vars:
    historic: true
  loop: "{{ range(harvester_historic_services)| list }}"
  loop_control:
    loop_var: service_index

- name: Create Live Harvesters
  include_tasks: harvester_live.yaml
  vars:
    live: true
  loop: "{{ range(harvester_live_services)| list }}"
  loop_control:
    loop_var: service_index
