# Project           : Gig Economy and its impact in Australia
# Team              : Group 33
# City              : Melbourne, Australia
# Authors           : Qing Feng Chye 770376, Sii Kim Lau 890511, Rohan Jahagirdar 835450
#                     Yun Liu 1046589, Shorye Chopra 689913
# Purpose           : Playbook Entry point for identifying ansible roles to be executed 
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    # - role: openstack-common
    #   tags:
    #     - infrastructure
    - role: openstack-volume
      tags:
        - infrastructure
    - role: openstack-security-group
      tags:
        - infrastructure
    - role: openstack-instance
      tags:
        - infrastructure

- hosts: SWARM
  vars_files:
    - host_vars/docker-swarm.yaml
  gather_facts: true
  become: yes

  roles:
    - role: swarm-common
      tags:
        - swarm
    - role: swarm-volumes
      tags:
        - swarm
    - role: swarm-setup
      tags:
        - swarm

# Below is helper role for populating the inventory file based on 
# the instances created above
# Uncomment when deploying or updating a new/existing application
# i.e - When planning on running an application-* role
# Ensure also to comment out above infrastructure related roles
# to quicken the playbook

# - hosts: localhost
#   vars_files:
#     - host_vars/nectar.yaml
#   gather_facts: false

#   roles:
#     - role: helper-inventory-populator

- hosts: SWARM
  vars_files:
    - host_vars/applications.yaml
  gather_facts: true
  become: yes

  roles:
    - role: application-haproxy
      tags:
        - haproxy
    - role: application-harvester
      tags:
        - harvester
    - role: application-couchdb
      tags:
      - couchdb